name: actions-secrets

on:
  push:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Install redis cli
        run:  sudo apt-get update -y && sudo apt-get install redis-tools -y
      
      - name: Testing redis container
        run:  redis-cli -h localhost -p 6379 ping
      
      - name: Print secret variable to test
        run:  echo "${{ secrets.TOKEN_SECRET }}"
      
      - name: Using node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
