name: actions-secrets

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret variable to test
        run:  echo "${{ secrets.TOKEN_SECRET }}"
      
      - name: Set up Checkout
        uses: actions/checkout@v4

      - name: Setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installing dependencies
        run:  npm install

      - name: Running testing
        run:  npm run test
  
      - name: Build Page
        run:  npm run build

  deploy:
    runs-on : ubuntu-latest
    needs   : build

    steps:
      - name: Deploy
        run : echo "Deploy..."
