name: actions-secrets

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret variable to test
        run:  echo "${{ secrets.TOKEN_SECRET }}"
      
      - name: Set up Checkout
        uses: actions/checkout@v4

      - name: Setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installing dependencies
        run:  npm install

      - name: Running testing
        run:  npm run test
  
      - name: Build Page
        run:  npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    runs-on : ubuntu-latest
    needs   : build
  
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url:  ${{ steps.deployment-pages.outputs.page_url }}

    steps:
      - name: Deploy
        id:   deployment-pages
        uses: actions/deploy-pages@v4
  
  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Notification to Slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
