name: actions-secrets

on:
  push:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret variable to test
        run:  echo "${{ secrets.TOKEN_SECRET }}"
      
      - name: Using node 18
        uses: actions/checkout@v4
        with:
          node-version: '18'

      - name: Installing dependencies
        run:  npm install

      - name: Running testing
        run:  npm run test
