name: actions-secrets

on:
  push:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print variable
        run:  echo "${{ secrets.TOKEN_SECRET }}"
      - name: Run action
        uses: actions/setup-node@v4
        with:
          node-version: '18'
