name: actions-secrets

on:
  push:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print variable
        run:  echo "${{ secret.TOKEN_SECRET }}"
        run:  echo "Goodbye Stranger"
